import { ICourse } from "modules/home/types/course";
import { IPayementCard } from "modules/home/types/payementCard";

export const fakeCourses: ICourse[] = [
  {
    createdAt: "2024-04-23T07:29:03.768Z",
    updatedAt: "2024-04-23T07:29:03.768Z",
    id: 47,
    title: "Graphic Design Masterclass - Learn GREAT Design",
    subtitle: "Intelligent Metal Ball",
    topic: "Refined Frozen Gloves",
    level: "Expert",
    duration: 10,
    description: { text: "hi" },
    subjects: ["Ai", "Machine learninig"],
    audience: ["strudnets"],
    requirements: ["Human (Optional)"],
    welcomeMessage: "maiores animi deleniti",
    congratsMessage: "aut modi placeat",
    price: 50,
    discount: 5,
    thumbnail: {
      id: "f39d372c-3552-4b62-a954-7957f9a7d497",
      path: "http://localhost:4000/api/v1/files/00477a23065504f1277c9.jpeg",
    },
    trailer: {
      id: "f39d372c-3552-4b62-a954-7957f9a7d497",
      path: "http://localhost:4000/api/v1/files/00477a23065504f1277c9.jpeg",
    },
    instructors: [
      {
        createdAt: "2024-04-17T07:10:53.938Z",
        updatedAt: "2024-04-17T07:10:53.938Z",
        deletedAt: null,
        id: 49,
        socialId: null,
        firstName: "souhail",
        lastName: "brahmi",
        username: null,
        title: null,
        bigoraphie: null,
        persenalWebsite: null,
        linkedin: null,
        twitter: null,
        facebook: null,
        instagram: null,
        whatsapp: null,
        youtube: null,
      },
      {
        createdAt: "2024-04-16T15:38:54.787Z",
        updatedAt: "2024-04-16T15:38:54.787Z",
        deletedAt: null,
        id: 31,
        socialId: null,
        firstName: "rayen",
        lastName: "mabrouk",
        username: null,
        title: null,
        bigoraphie: null,
        persenalWebsite: null,
        linkedin: null,
        twitter: null,
        facebook: null,
        instagram: null,
        whatsapp: null,
        youtube: null,
      },
    ],
  },
];
export const oldCards: IPayementCard[] = [
  {
    id: 1,
    type: "masterCard",
    number: "1234 **** **** ****",
    expiry: "12/24",
    owner: "John Doe",
    cvc: 123,
  },
  {
    id: 2,
    type: "visa",
    number: "4321 **** **** ****",
    expiry: "12/24",
    owner: "Souhail Brahmi",
    cvc: 123,
  },
];
